BIGQUERY_PROJECT: "govuk-content-data"
BIGQUERY_CLIENT_EMAIL: "govuk-content-data-ga4@govuk-content-data.iam.gserviceaccount.com"
BIGQUERY_PRIVATE_KEY: |-
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCq/PexwxiPtJRi
  MlmK9EfxpG94e8AClT7ZqL3J0wuWQfk2xi9rEa2Zd3RCsp6t6J99N5qOwmgF/bpF
  VaDwI4eVsTkqjJAq0tLnmqyZChBZFxtwMaLstPxl4WTvNw28ndswKRmeMr30eZXz
  fuaGhyNCsynJdSwV2sygfN+lxtXFX/W2qrVtbdzjcKzFj7bYV55T/GWERmeA/Nee
  UBCJ19pB/+kPBuF72fE8kRP4yTFY23A4vIONcbt/NzYDhbEsiib7uz0I6ZTm0uGa
  RebCO1qUkZycdC3feaXKbOYKMqi6hhoBh5dcoSb03Sv1p1Yl7gKPc9EiX8iWtZPv
  7Qh0Pqa/AgMBAAECggEAPAT8+yh07Ciid0+eL9Dsmg0y1bN2pFF4FNYO/JO4uv8g
  eBIcHfTAH6EXLbxeR8Rii4Ujmx3xfrzgECttCS4njyt82gsqJeYIAyU/lZ67O1KJ
  npnFy1oCSM7T68ZC66Trhh2/MNE17WVqdeTjDXDNN0IFloIrPeamMmVy6dGAQz4G
  AZU1GezbCerjpeElNGoJjGzXqe3zqm5frhF82HkKMduWHCwwFEnnoSsWQCFjNKzW
  gsCspJ+AuOUNhIWqrQFRuqA4xR38DeS3mzmlezMepbOiDiYCLT3CbOSR2NQ+N7M3
  EHQfHFzPlKkFXDXiSJf1P/utA4rUPGTFa2w/jT8sqQKBgQDwuSUsPSICaSvyt3G9
  hRNWP59LO2toktRxg2yEEhWMS7XyPxtQkAIAyupFoOoj1fI7hgvv6QkTqtxmcULx
  Tc2cBnsSp632XplJ/L//0VVXqFEKkg/YuPfEuRfnUmaRqys/uNxNetUiwrqD/hoJ
  TC9P3lf94dTfSPCbo++Xv5e2OQKBgQC11uMzTJ5CMgv/8AdQ3AZWJtI0T4DYQV5x
  JoWG6k2ttIX6qk2orL8Yp7RmbNdJffKAXoCe47uHiVSdBTgaZYLI18W+p44ZmdOs
  kgqcHzO4xCG5w+1VpJGm0K1Irtw4T9UwL8MRqBvicEet+q/51YIHS4lOFsZCxFXZ
  zDU5+4aEtwKBgBbvTN9eI7NfGdTSLYAFAcah4SdlzeH0u1DlWJ1sq6jmPbuKz6tp
  TQeOTau8nRI0/BM3vkNpTHgXO1B3Ug1zgDdxVqB8YVKryKcH8bMJ2ruzSaVcLS5U
  0SZpDCH589PFHyW/Ex4+qbfaHbMdrpVcMNXHNVL3BTUQ2fu6LsWid23hAoGBAJWT
  ht7K1p+S9WX5drsf0iKJ2n1nLJA27U3cJxg8odsSVOdFsY3fU24ffXiHbWwpqxHH
  KrwIjljGMZDcGzMzbypwu1vCDlSmwYUBuLKFxBDnXOqm7RJ2xczXeMMB+2pi2PXD
  RA3BH/ba70uAm8LByyzfCLnwZ/PB9vCqVto0OYnvAoGAbvhYbU4jdunqHsynW8yE
  UBWYJfEnGSfEouqs5fA6o74KsGWZgv/XuRsA7XnFx+XN2eOqzbgSuj64O0YOUsF1
  lrUJKVUbdyMPTA3s9Pv4Ms39qsvevw6Gm5ZA1yP3P35l1HbfLMDokzYObJGLK7Sq
  6w59s0N6ystNu98zM5zJ+fE=
  -----END PRIVATE KEY-----
